segmentation_fingerprint:
  image_path: /home/ubuntu/m15kh/Image_Segmentation/Finger_Data/Dataset/images
  image_extention: png
  mask_path: /home/ubuntu/m15kh/Image_Segmentation/Finger_Data/Dataset/masks
  mask_extention: png
  is_skeleton: false
  is_ridge_white: false
  checkpoint_path: checkpoints/
  experiment_path: results/segmentation_train
  height: 512
  width: 512
  batch_size: 7
  epochs: 70
  learning_rate: 1e-4
  val_percent: 0.1
