segmentation_fingerprint:
  image_path: /home/ubuntu/m15kh/U_NET/U_Net_v2/dataset/patch/patch_images
  image_extention: png
  mask_path: /home/ubuntu/m15kh/U_NET/U_Net_v2/dataset/patch/patch_masks
  mask_extention: png
  is_skeleton: false
  is_ridge_white: false
  checkpoint_path: checkpoints/
  experiment_path: results/segmentation_train
  height: 1360
  width: 1360
  batch_size: 3
  epochs: 70
  learning_rate: 1e-4
  val_percent: 0.2
