segmentation_fingerprint:
  input_dir: /home/ubuntu/m15kh/PFR/output/test
  file_extention: png
  checkpoint_path: /home/ubuntu/m15kh/PFR/PFR/src/extractor/segmentation/checkpoints/extraction/segmentation/segmentation_epoch_64_loss_0.154.pth
  output_path: /home/ubuntu/m15kh/PFR/output/result/
  batch_size: 1
