import argparse


class ConfigInference():
    def __init__(self)->None:
        self.config = argparse.Namespace(**{
            "image_size" : None,
            "seed": 42,
            "compute_fid": False,
            "num_channels": 2,
            "centered": True,
            "use_geometric": False,
            "beta_min": 0.1,
            "beta_max": 20.0,
            "num_channels_dae": 64,
            "n_mlp": 3,
            "ch_mult": [1, 1, 2, 2, 4, 4],
            "num_res_blocks": 2,
            "attn_resolutions": [16],
            "dropout": 0.0,
            "resamp_with_conv": False,
            "conditional": True,
            "fir_kernel": [1, 3, 3, 1],
            "fir": True,
            "skip_rescale": True,
            "resblock_type": 'biggan',
            "progressive": 'none',
            "progressive_input": 'residual',
            "progressive_combine": 'sum',
            "embedding_type": 'positional',
            "fourier_scale": 16.0,
            "not_use_tanh": False,
            "dataset": "Fingerprint",
            "nz": 100,
            "num_timesteps": 4,
            "z_emb_dim": 256,
            "t_emb_dim": 256,
            "batch_size": 1,
            "lr_g": 1.5e-4,
            "beta1": 0.5,
            "beta2": 0.9,
            "contrast1": "T1",
            "contrast2": "T2",
            "source": "T2"
            })

class ConfigTrain():
    def __init__(self)->None:
        self.config = argparse.Namespace(**{    
            "image_size" : None,                       
            "seed" : 1024,
            "resume" : False,
            "num_channels" : 2,
            "centered" : True,
            "use_geometric" : False,
            "beta_min" : 0.1,
            "beta_max" : 20.0,
            "num_channels_dae" : 64,
            "n_mlp" : 3,
            "ch_mult" : [1, 1, 2, 2, 4, 4],
            "num_res_blocks" : 2,
            "attn_resolutions" : [16],
            "dropout" : 0.0,
            "resamp_with_conv" : True,
            "conditional" : True,
            "fir" : True,
            "fir_kernel" : [1, 3, 3, 1],
            "skip_rescale" : True,
            "resblock_type" : 'biggan',     
            "progressive" : 'none',     
            "progressive_input" : 'residual',     
            "progressive_combine" : 'sum',     
            "embedding_type" : 'positional',     
            "fourier_scale" : 16.0,     
            "not_use_tanh" : False,        
            "nz" : 100,     
            "num_timesteps" : 4,     
            "z_emb_dim" : 256,     
            "t_emb_dim" : 256,        
            "ngf" : 64,     
            "lr_g" : 1.6e-4,     
            "lr_d" : 1e-4,     
            "beta1" : 0.5,     
            "beta2" : 0.9,     
            "no_lr_decay" : False,     
            "use_ema" : True,     
            "ema_decay" : 0.999,     
            "r1_gamma" : 1.0,     
            "lazy_reg" : 10,     
            "lambda_l1_loss" : 0.5,    
            "node_rank" : 0,     
            "local_rank" : 0,     
            "master_address" : '127.0.0.1',     
            "contrast1" : "T1",     
            "contrast2" : "T2",     
            "port_num" : '6021',                                                                                   
            })