metrics:
  gt_dir: /home/ubuntu/m15kh/Image_Segmentation/Validation/masks/
  pred_dir: /home/ubuntu/m15kh/Image_Segmentation/U_Net_v2/validation_inference/unet
  save_dir: /home/ubuntu/m15kh/own/segmentation_metrics/metrics_result/unet
  resize_target: gt  # Options: 'gt' or 'pred'
