diffgan:
  input_dir: /home/ubuntu2/m15kh/Image_Segmentation/test_palm_ex_padding
  file_extention: png
  output_path: /home/ubuntu2/m15kh/Image_Segmentation/results/difgan
  checkpoint_path: /home/ubuntu2/m15kh/Image_Segmentation/checkpoints/gen_diffusive_1_15.pth
  step: 100
  device: gpu
  batch_size: 10
