diffgan:
  image_size: 1024
  input_dir: /home/ubuntu/m15kh/Image_Segmentation/Finger_Data/Dataset/images
  output_dir: /home/ubuntu/m15kh/Image_Segmentation/FineTune_SynDiff/output
  batch_size: 5
  num_epochs: 16
  save_ckpt_every: 1          #How frequently save checkpoints
  image_extentions: png
  mask_extentions: png
  mpoint_extentions: mnt      #choices = [npy, mnt]
  num_proc_node: 1
  num_process_per_node: 1     #Number of GPUs 
  full_image_train: True  #Whether you want to train the model in full-image input mode or patch-wise input mode
                              #please also change the image_size parameter to a higher number when using full-image training mode.
  crop_input: True      #Set this True when you want train full-image and you want to crop the input image based on the mask to avoid noise.
  use_mpoints: False         #Set True if you want to use Mpoints during training.  
  background_color_of_mask: 1 #["White : 0, Black : 1"]
  fingerprint_type: visible #visible       #[visible or latent]
